webonary changes to browse by semantic domains from api
sillsdev/webonary pull request #50
Opened 2020-05-19 04:21 UTC by hanatgit

2020-05-20 23:46 UTC, phillip-hopper requested changes

2020-05-20 23:46 UTC, phillip-hopper commented on wordpress/wp-content/plugins/sil-dictionary-webonary/include/browseview_func.php
> +			array_multisort(array_keys($arrDomains), SORT_NATURAL, $arrDomains);
If this is just sorting by key, I would use this:
```
ksort($arrDomains, SORT_NATURAL);
```

2020-05-21 15:38 UTC, hanatgit commented on wordpress/wp-content/plugins/sil-dictionary-webonary/include/browseview_func.php
> +			array_multisort(array_keys($arrDomains), SORT_NATURAL, $arrDomains);
Nice catch! Done. 
(Fyi, I was using arrDomains as an array of array items initially, and so had to use multisort, then later I refactored to make arrDomains into a hash, but forgot to simplify to using ksort.)

2020-05-21 15:42 UTC, phillip-hopper approved these changes

2020-05-21 17:40 UTC, merged